name       : xorg-driver-video-qxl
version    : 0.1.5
release    : 5
source     :
    - git|https://anongit.freedesktop.org/git/xorg/driver/xf86-video-qxl.git : 9a7eb40fa23b908d9f62a8f04933fdafd04d6b88
license    : MIT
component  : xorg.driver
summary    : QXL Virtual GPU for Spice Virtualisation
description: |
    QXL Virtual GPU for Spice Virtualisation
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(spice-server)
    - pkgconfig(libpcsclite)
    - pkgconfig(libudev)
    - pkgconfig(spice-protocol)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86dgaproto)
    - pkgconfig(xfont2)
    - pkgconfig(xorg-macros)
optimize   : no-bind-now
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
