name       : xorg-driver-video-qxl
version    : 0.1.5
release    : 9
source     :
    - git|https://anongit.freedesktop.org/git/xorg/driver/xf86-video-qxl.git : ee8f904ab0d590c741e640e9548c472e6a58b3cc
license    : MIT
component  : xorg.driver
summary    : QXL Virtual GPU for Spice Virtualisation
description: |
    QXL Virtual GPU for Spice Virtualisation
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(spice-server)
    - pkgconfig(libpcsclite)
    - pkgconfig(libudev)
    - pkgconfig(spice-protocol)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86dgaproto)
    - pkgconfig(xfont)
    - pkgconfig(xorg-macros)
optimize   : no-bind-now
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
