name       : xorg-driver-video-qxl
version    : 0.1.4
release    : 1
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-qxl-0.1.4.tar.gz : df179263219e80c50a0a7a5f7f05087bc3312f7e63128120a7caa64e3e1e05c8
license    : MIT
component  : xorg.driver
summary    : QXL Virtual GPU for Spice Virtualisation
description: |
    QXL Virtual GPU for Spice Virtualisation
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(spice-server)
    - pkgconfig(libpcsclite)
    - pkgconfig(libudev)
    - pkgconfig(spice-protocol)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
    - pkgconfig(fontsproto)
    - pkgconfig(xf86dgaproto)
    - pkgconfig(xfont)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
