name       : xorg-driver-video-qxl
version    : 0.1.5
release    : 21
source     :
    - git|https://gitlab.freedesktop.org/xorg/driver/xf86-video-qxl.git : 52c421c650f8813665b31890df691b31fabc366a
license    : MIT
component  : xorg.driver
summary    : QXL Virtual GPU for Spice Virtualisation
description: |
    QXL Virtual GPU for Spice Virtualisation
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(spice-server)
    - pkgconfig(libpcsclite)
    - pkgconfig(libudev)
    - pkgconfig(spice-protocol)
    - pkgconfig(xext)
    - pkgconfig(xfont2)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
setup      : |
    %patch -p1 < $pkgfiles/buildfix.diff
    %patch -p1 < $pkgfiles/0001-configure-Simplify-fragile-libdrm-detection.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/xorg.conf $installdir/usr/share/X11/xorg.conf.d/10-qxl.conf
